#!/bin/sh
if test "$1" = remove -a "$1" = abort-install -a "$1" = disappear;
then
  dpkg-divert --no-rename --remove --package rpikernelhack /boot/firmware/overlays/wlmio.dtbo
  rm /boot/firmware/overlays/wlmio.dtbo

  dpkg-divert --no-rename --remove --package rpikernelhack /boot/firmware/overlays/wlmio-pi5.dtbo
  rm /boot/firmware/overlays/wlmio-pi5.dtbo
fi
