#!/bin/sh
set -e

if [ -d /boot/firmware ]; then
	BOOT_PATH=/boot/firmware
else
	BOOT_PATH=/boot
fi

if [ "$1" = remove ] || [ "$1" = abort-install ] || [ "$1" = disappear ]; then
  rm $BOOT_PATH/wlmio.txt
fi
